name: update bar-data.json

on:
  schedule:
    - cron: "*/15 * * * *" # every 15 minutes
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "scripts/**"
      - ".github/workflows/update.yml"
      - "package.json"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate bar-data.json
        env:
          USER_AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome Safari"
        run: |
          npm run update
          echo "Preview:"
          cat bar-data.json

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add bar-data.json
            git commit -m "chore: refresh bar-data.json [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
